api/urls.py
from django.urls import path
from .views import todos_view

app_name = "api"
urlpatterns = [
    path('todos/', todos_view, name='todos'),
]

forms_app/urls.py
from django.urls import path
from .views import contatti, elimina_contatto, listacontatti, modifica_contatto

app_name = 'forms_app'

urlpatterns = [
    path('contatti/', contatti, name='contatti'),
    path('lista/', listacontatti, name='listacontatti'),
    path('elimina/<int:id>/', elimina_contatto, name='elimina_contatto'),
    path('modifica/<int:id>/', modifica_contatto, name='modifica_contatto'),
]

news/urls.py
from django.urls import path
from .views import home, articoloDetailView, listaArticoli, queryBase

app_name = 'news'

urlpatterns = [
    path('', home, name="homepage"),
    path('articoli/<int:pk>', articoloDetailView, name="articolo_detail"),
    path('lista_articoli/', listaArticoli, name="lista_articoli"),
    path('lista_articoli/<int:pk>', listaArticoli, name="lista_articoli"),
    path('query_base/', queryBase, name="query_base"),
]

prima_app/urls.py
from django.urls import path
from prima_app.views import homepage, welcome, lista, chi_siamo, variabili, index

app_name="prima_app"
urlpatterns=[
    path('homepage', homepage, name='homepage'),
    path('welcome', welcome, name='welcome'),
    path('lista', lista, name='lista'),
    path('chi_siamo', chi_siamo, name='chi_siamo'),
    path('variabili', variabili, name='variabili'),
    path('index', index, name='index'),

]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import base

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',base,name='base'),
    path('prima_app/',include("prima_app.urls",namespace="prima_app")),
    path('seconda_app/',include("seconda_app.urls",namespace="seconda_app")),
    path('news/',include("news.urls",namespace="news")),
    path('corsi_formazione/',include("corsi_formazione.urls",namespace="corsi_formazione")),
    path('forms_app/',include("forms_app.urls",namespace="forms_app")),
    path('api/',include("api.urls",namespace="api")),
]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns+=[
    path('accounts/', include('django.contrib.auth.urls')),
]   

seconda_app/urls.py
from django.urls import path
from .views import es_if, if_else_elif, es_for

app_name = "seconda_app"
urlpatterns = [
    path('es_if',es_if,name="es_if"),
    path('if_else_elif',if_else_elif,name="if_else_elif"),
    path('es_for',es_for,name="es_for"),
    ]

primo_progetto/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib import messages


# Create your views here.
def base(request):
    return render(request,"base.html")

primo_progetto/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="it">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous" />
    <!-- Includi Font Awesome CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />

    <title>
      {% block title %}
        Primo progetto
      {% endblock %}
    </title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Primo progetto</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Prima app</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="{% url 'prima_app:chi_siamo' %}">Chi siamo</a>
              <a class="dropdown-item" href="{% url 'prima_app:homepage' %}">Homepage</a>
              <a class="dropdown-item" href="{% url 'prima_app:index' %}">Index</a>
              <a class="dropdown-item" href="{% url 'prima_app:lista' %}">Lista</a>
              <a class="dropdown-item" href="{% url 'prima_app:variabili' %}">Variabili</a>
              <a class="dropdown-item" href="{% url 'prima_app:welcome' %}">Welcome</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Seconda app</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="{% url 'seconda_app:es_for' %}">for</a>
              <a class="dropdown-item" href="{% url 'seconda_app:es_if' %}">if</a>
              <a class="dropdown-item" href="{% url 'seconda_app:if_else_elif' %}">if else elif</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">News</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="{% url 'news:homepage' %}">Home</a>
              <a class="dropdown-item" href="{% url 'news:lista_articoli' %}">Lista</a>
              <a class="dropdown-item" href="{% url 'news:query_base' %}">Query</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Corsi di Formazione</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="{% url 'corsi_formazione:index' %}">Index</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Contatti</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="{% url 'forms_app:contatti' %}">Contattaci</a>
              <a class="dropdown-item" href="{% url 'forms_app:listacontatti' %}">Lista contatti</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">API</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="{% url 'api:todos' %}">Todos</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Login</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="{% url 'login' %}">Login</a>
            </div>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container my-4">
      {% block content %}

      {% endblock %}
      {% block script %}

      {% endblock %}
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!--  Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
     -->
  </body>
</html>

primo_progetto/templates/index_root.html
<!DOCTYPE html>
<html lang="it">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
</head>
<body>
    <h1><a href="/admin">Pannello admin</a></h1>
    <h1><a href="{% url 'prima_app:index'%} ">Index</a></h1>
</body>
</html>